import { MigrationInterface, QueryRunner } from 'typeorm';

export class autogeneratedUserId1653169465889 implements MigrationInterface {
  name = 'autogeneratedUserId1653169465889';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE SEQUENCE IF NOT EXISTS "user_id_seq" OWNED BY "user"."id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "user" ALTER COLUMN "id" SET DEFAULT nextval('"user_id_seq"')`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "user" ALTER COLUMN "id" DROP DEFAULT`,
    );
    await queryRunner.query(`DROP SEQUENCE "user_id_seq"`);
  }
}
